ARG ALPINE_VERSION=3.10

FROM aprimediet/alpine:${ALPINE_VERSION} AS base
LABEL maintainer="<Muhamad Aditya Prima> aprimediet@gmail.com"

WORKDIR /root

# Add user and group www-data
RUN addgroup -g 1010 www-data
RUN adduser -u 1010 -D -H -h /usr/www -G www-data www-data
RUN adduser www-data tty

# INSTALL php7
RUN --mount=type=cache,target=/var/cache/apk \
    apk add --update \
    git php7 php7-bz2 php7-bcmath php7-common \
    php7-ctype php7-curl php7-dev \
    php7-dom php7-embed php7-exif php7-fileinfo \
    php7-fpm php7-ftp php7-gd php7-gettext php7-gmp \
    php7-iconv php7-intl php7-ldap php7-openssl php7-pear \
    php7-pspell php7-session php7-simplexml php7-snmp php7-soap \
    php7-sockets php7-tidy php7-tokenizer php7-xml php7-xmlreader \
    php7-xmlwriter php7-xsl php7-zip php7-json php7-phar

# Download composer
ADD https://getcomposer.org/installer ./composer-setup.php

RUN php composer-setup.php && mv composer.phar /usr/local/bin/composer && rm -f composer-setup.php

FROM base AS build

# COPY Configuration File
RUN mkdir -p /var/run/php

ADD ./etc/php7 /etc/php7
ADD ./etc/services.d/php-fpm7 /etc/services.d/php-fpm7

# Clean APK Cache
RUN rm -rf /var/cache/apk/*

EXPOSE 9000