ARG PHP_VERSION=8.1

FROM aprimediet/php:${UBUNTU_VERSION}
LABEL maintainer="<Muhamad Aditya Prima> aprimediet@gmail.com"

ARG PHP_VERSION=8.1

WORKDIR /root

# UPDATE DEPENDENCIES FIRST
RUN --mount=type=cache,target=/var/cache/apt/archives \
    apt -y update && apt -y upgrade

# INSTALL BASE DEPENDENCIES
RUN --mount=type=cache,target=/var/cache/apt/archives \
    apt -y install \
    php${PHP_VERSION}-