ARG ALPINE_VERSION=3.5

FROM aprimediet/nginx:alpine-${ALPINE_VERSION}
LABEL maintainer="<Muhamad Aditya Prima> aprimediet@gmail.com"

# INSTALL php5
# RUN apk update && apk upgrade && \
RUN apk add --update --no-cache \
    git php5 php5-bz2 php5-bcmath php5-common \
    php5-ctype php5-curl php5-dev \
    php5-dom php5-embed php5-exif  \
    php5-fpm php5-ftp php5-gd php5-gettext php5-gmp \
    php5-iconv php5-intl php5-ldap php5-openssl php5-pear \
    php5-pspell php5-snmp php5-soap \
    php5-sockets php5-xml php5-xmlreader \
    php5-xsl php5-zip php5-json
# php5-dbg php5-fileinfo php5-session php5-simplexml
# php5-tidy php5-tokenizer php5-xmlwriter 

# COPY Configuration File
RUN mkdir -p /var/run/php
RUN mkdir -p /var/log/php5
RUN touch /var/log/php5/error.log
ADD ./etc/nginx /etc/nginx
ADD ./etc/services.d/php-fpm5 /etc/services.d/php-fpm5
ADD usr /usr

EXPOSE 80