ARG ALPINE_VERSION=3.5

FROM aprimediet/alpine:${ALPINE_VERSION}
LABEL maintainer="<Muhamad Aditya Prima> aprimediet@gmail.com"

# Add user and group www-data
RUN mkdir /usr/www
RUN addgroup -g 1010 www-data
RUN adduser -u 1010 -D -H -h /usr/www -G www-data www-data
RUN adduser www-data tty

# INSTALL php5
# RUN apk update && apk upgrade && \
RUN apk add --update --no-cache \
    git php5 php5-bz2 php5-bcmath php5-common \
    php5-ctype php5-curl php5-dev \
    php5-dom php5-embed php5-exif  \
    php5-fpm php5-ftp php5-gd php5-gettext php5-gmp \
    php5-iconv php5-intl php5-ldap php5-openssl php5-pear \
    php5-pspell php5-snmp php5-soap \
    php5-sockets php5-xml php5-xmlreader \
    php5-xsl php5-zip php5-json

# COPY Configuration File
RUN mkdir -p /var/run/php

ADD ./etc/php5 /etc/php5
ADD ./etc/services.d/php-fpm5 /etc/services.d/php-fpm5

EXPOSE 80