ARG ALPINE_VERSION=3.18

FROM aprimediet/alpine:${ALPINE_VERSION}
LABEL maintainer="<Muhamad Aditya Prima> aprimediet@gmail.com"

# Add user and group www-data
RUN mkdir /usr/www
# RUN addgroup -g 1010 www-data
RUN adduser -u 1010 -D -H -h /usr/www -G www-data www-data
RUN adduser www-data tty

# INSTALL php5
# RUN apk update && apk upgrade && \
RUN apk add --update --no-cache \
    git php82 php82-bz2 php82-bcmath php82-common \
    php82-ctype php82-curl php82-dev \
    php82-dom php82-embed php82-exif php82-fileinfo \
    php82-fpm php82-ftp php82-gd php82-gettext php82-gmp \
    php82-iconv php82-intl php82-ldap php82-openssl php82-pear \
    php82-pspell php82-session php82-simplexml php82-snmp php82-soap \
    php82-sockets php82-tidy php82-tokenizer php82-xml php82-xmlreader \
    php82-xmlwriter php82-xsl php82-zip php82-dbg php82-json

# COPY Configuration File
RUN mkdir -p /var/run/php

ADD ./etc/php82 /etc/php82
ADD ./etc/services.d/php-fpm82 /etc/services.d/php-fpm82

EXPOSE 9000