ARG ALPINE_VERSION=3.18

FROM aprimediet/alpine:${ALPINE_VERSION}
LABEL maintainer="<Muhamad Aditya Prima> aprimediet@gmail.com"

# Add user and group www-data
RUN mkdir /usr/www
# RUN addgroup -g 1010 www-data
RUN adduser -u 1010 -D -H -h /usr/www -G www-data www-data
RUN adduser www-data tty

# INSTALL php5
# RUN apk update && apk upgrade && \
RUN apk add --update --no-cache \
    git php81 php81-bz2 php81-bcmath php81-common \
    php81-ctype php81-curl php81-dev \
    php81-dom php81-embed php81-exif php81-fileinfo \
    php81-fpm php81-ftp php81-gd php81-gettext php81-gmp \
    php81-iconv php81-intl php81-ldap php81-openssl php81-pear \
    php81-pspell php81-session php81-simplexml php81-snmp php81-soap \
    php81-sockets php81-tidy php81-tokenizer php81-xml php81-xmlreader \
    php81-xmlwriter php81-xsl php81-zip php81-json

# COPY Configuration File
RUN mkdir -p /var/run/php

ADD ./etc/php81 /etc/php81
ADD ./etc/services.d/php-fpm82 /etc/services.d/php-fpm82

EXPOSE 9000